### ISSUE TITLE
Removed '-' from arguments

### ISSUE THREAD

**Issue by goek-han** [buty4649/osc-fish-complete#2]
Hello buty4649 ,

firstly, thank you for this tool! One thing that is not correct for me is that in some arguments the additional '-' is missing, e.g. `openstack server show --fitwidth` instead of `--fit-wdith`. 

I amateurishly changed this line https://github.com/buty4649/osc-fish-complete/blob/master/osc_fish_complete/complete.py#L16 to
```
o = opt.replace("-", "-")
```
and it works for me: the multi-word arguments all have the '-'. 

But I'm wondering why you inserted the replace function?

**Comment by buty4649** [comment]
hi! @goek-han 

Thank you for bug reporting!
Please try it out as it has been fixed in v0.2.0.

---
> But I'm wondering why you inserted the replace function?

The reason is that __fish_seen_subcommand_from adds `--`, so it was necessary to remove `-` in advance.
The following image is the output when not replaced.

![image](https://user-images.githubusercontent.com/1275643/233256391-b2f8a2d9-4e58-4c40-9c13-ed0b22928143.png)

The problem was solved by deleting only the leading `--` in v0.2.0.
![image](https://user-images.githubusercontent.com/1275643/233256625-3f359ee0-3c75-4b38-b725-75d407ddd5ed.png)

**Comment by goek-han** [comment]
Thanks @buty4649 for the fix and for the explanation. It works perfectly now!
